import mongoose from 'mongoose';

const clothesSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true, // Removes whitespace from both ends of a string
    },
    brand: {
      type: String,
      required: true,
      trim: true,
    },
    size: {
      type: String,
      // Enum ensures size must be one of these values
      enum: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      default: 'M', // Default size if none is provided
      required: true,
    },
    category: {
      type: String,
      trim: true,
      default: 'Unknown', // Default category if none is provided
      required: true,
      // --- MODIFIED ENUM ---
      // Added the categories generated by the bulk push script
      // to the original list.
      enum: [
          'Modern',
          'Modern/Old_Money',
          'Smart_Casual/Casual_Everyday',
          'Smart_Casual',
          'Casual_Everyday'
          // Add 'Misc' if your script could potentially generate it, although unlikely with current mapping
          // 'Misc'
        ],
      // --- END MODIFICATION ---
    },
    price: {
      type: Number,
      required: true,
      min: [0, 'Price cannot be negative'], // Ensure price is not negative
    },
    
    upper: {
      type: Boolean,
      default: false,
    },

    lower: {
      type: Boolean,
      default: false,
    },
    
    imageUrl: {
      type: String,
      trim: true,
      default: '', // Default image URL if none provided (though required is true)
      required: true,
    },
    lower: {
      type: Boolean,
      default: false, // Default to false if not specified
    },
    upper: {
      type: Boolean,
      default: false, // Default to false if not specified
    },

  },
  {

    timestamps: true,
    collection: 'clothes',
  }
);

// Optional: Add indexes for faster querying on frequently searched fields
// clothesSchema.index({ brand: 1 });
// clothesSchema.index({ category: 1 });
// clothesSchema.index({ price: 1 });

// Create the Mongoose model from the schema
const Clothes = mongoose.models.Clothes || mongoose.model('Clothes', clothesSchema);

// Export the model to be used elsewhere in your application
export default Clothes;